samples/kegbot_mock/config/routes.rb
KegbotMock::Application.routes.draw do
  resources :drinks

end

samples/kegbot_mock/app/models/drink.rb
class Drink < ActiveRecord::Base
end

samples/kegbot_mock/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

samples/kegbot_mock/app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drinks }
    end
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
    @drink = Drink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @drink }
    end
  end

  # GET /drinks/new
  # GET /drinks/new.json
  def new
    @drink = Drink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drink }
    end
  end

  # GET /drinks/1/edit
  def edit
    @drink = Drink.find(params[:id])
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(params[:drink])

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render json: @drink, status: :created, location: @drink }
      else
        format.html { render action: "new" }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drinks/1
  # PUT /drinks/1.json
  def update
    @drink = Drink.find(params[:id])

    respond_to do |format|
      if @drink.update_attributes(params[:drink])
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink = Drink.find(params[:id])
    @drink.destroy

    respond_to do |format|
      format.html { redirect_to drinks_url }
      format.json { head :no_content }
    end
  end
end

samples/kegbot_mock/app/helpers/application_helper.rb
module ApplicationHelper
end

samples/kegbot_mock/app/helpers/drinks_helper.rb
module DrinksHelper
end

samples/kegbot_mock/app/views/drinks/_form.html.erb
<%= form_for(@drink) do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :volume_ml %><br />
    <%= f.text_field :volume_ml %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :ticks %><br />
    <%= f.number_field :ticks %>
  </div>
  <div class="field">
    <%= f.label :session_id %><br />
    <%= f.text_field :session_id %>
  </div>
  <div class="field">
    <%= f.label :our_tie %><br />
    <%= f.text_field :our_tie %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :keg_id %><br />
    <%= f.text_field :keg_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

samples/kegbot_mock/app/views/drinks/edit.html.erb
<h1>Editing drink</h1>

<%= render 'form' %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %>

samples/kegbot_mock/app/views/drinks/index.html.erb
<h1>Listing drinks</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Volume ml</th>
    <th>Url</th>
    <th>Ticks</th>
    <th>Session</th>
    <th>Our tie</th>
    <th>Duration</th>
    <th>Keg</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drinks.each do |drink| %>
  <tr>
    <td><%= drink.status %></td>
    <td><%= drink.volume_ml %></td>
    <td><%= drink.url %></td>
    <td><%= drink.ticks %></td>
    <td><%= drink.session_id %></td>
    <td><%= drink.our_tie %></td>
    <td><%= drink.duration %></td>
    <td><%= drink.keg_id %></td>
    <td><%= link_to 'Show', drink %></td>
    <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
    <td><%= link_to 'Destroy', drink, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Drink', new_drink_path %>

samples/kegbot_mock/app/views/drinks/new.html.erb
<h1>New drink</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

samples/kegbot_mock/app/views/drinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @drink.status %>
</p>

<p>
  <b>Volume ml:</b>
  <%= @drink.volume_ml %>
</p>

<p>
  <b>Url:</b>
  <%= @drink.url %>
</p>

<p>
  <b>Ticks:</b>
  <%= @drink.ticks %>
</p>

<p>
  <b>Session:</b>
  <%= @drink.session_id %>
</p>

<p>
  <b>Our tie:</b>
  <%= @drink.our_tie %>
</p>

<p>
  <b>Duration:</b>
  <%= @drink.duration %>
</p>

<p>
  <b>Keg:</b>
  <%= @drink.keg_id %>
</p>


<%= link_to 'Edit', edit_drink_path(@drink) %> |
<%= link_to 'Back', drinks_path %>

samples/kegbot_mock/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KegbotMock</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>